version: "3"
services:
  app:
    container_name: autodepoly-master
    restart: unless-stopped
    build: .  # '点'代表当前目录
    env_file:
      - .env
    environment:
      - DJANGO_ENV_FILE=/code/.env.master
    command: bash -c "python3 manage.py collectstatic --no-input && python3 manage.py makemigrations && python3 manage.py migrate && gunicorn --timeout=30 --workers=4 --bind :8000 autoDepoly.wsgi:application"
    volumes:
      - .:/code
      - /www/autoDepoly-master/static:/code/collected_static
    expose:
      - "8000"
    networks:
      - nginx_default
      
networks:
  nginx_default:
    external: true