version: "3"
services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - /www/autoDepoly/static:/code/collected_static
    networks:
      - nginx_default
  app:
    restart: unless-stopped
    build: .  # '点'代表当前目录
    env_file:
      - .env
    command: bash -c "python3 manage.py collectstatic --no-input && python3 manage.py makemigrations && python3 manage.py migrate && gunicorn --timeout=30 --workers=4 --bind :8000 autoDepoly.wsgi:application"
    volumes:
      - .:/code
      - /www/autoDepoly/static:/code/collected_static
    expose:
      - "8000"
    networks:
      - nginx_default
    depends_on:
      - nginx-proxy-manager
      
networks:
  nginx_default:
    driver: bridge