# Generated by Django 5.2 on 2025-04-25 02:26

from django.db import migrations


def add_initial_data(apps, schema_editor):
    News = apps.get_model('news', 'News')
    if not News.objects.filter(pk=1).exists():
        News.objects.create(
            title="The First News",
            content="This is a news content",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_data),
    ]
