# Generated by Django 5.2 on 2025-04-25 00:42

from django.db import migrations


def add_initial_data(apps, schema_editor):
    Blog = apps.get_model('blog', 'Blog')
    if not Blog.objects.filter(pk=1).exists():
        Blog.objects.create(
            name="Test Post",
            description="This is a test post",
        )


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_initial_data),
    ]
